# @package _global_

model:
  type: GeometryTransformer
  encoder:
    type: hrnet32
    pretrained: True
  view_scales: [4, 8, 16]
  num_layers: [2, 3, 2, 1]
  criterions: [ce_ssc, sem_scal, geo_scal]
