# @package _global_

model:
  type: Symphonies
  cfgs:
    embed_dims: 128
    encoder:
      type: MMDetWrapper
      cfgs:
        config_path: maskdino/configs/maskdino_r50_8xb2-panoptic-export.py
        custom_imports: maskdino
        checkpoint_path: ../../backups/maskdino_r50_50e_300q_panoptic_pq53.0.pth
    criterions: [ce_ssc, sem_scal, geo_scal, frustum]

solver:
  optimizer:
    paramwise_cfg:
      - name: encoder
        lr_mult: 0.1
