# @package _global_

data:
  datasets:
    type: KITTI360
    splits: [train, val, test]
    cfgs:
      data_root: /home/users/haoyi.jiang/data/kitti_360
      label_root: /home/users/haoyi.jiang/data/kitti_360/labels
      depth_root: /home/users/haoyi.jiang/data/kitti_360/depth
      frustum_size: 8
  loader:
    batch_size: 1
    num_workers: 4

model:
  cfgs:
    channels: 64
    scene_size: [256, 256, 32]
    volume_scale: 2
    num_classes: 19
    image_shape: [376, 1408]
solver:
  evaluator:
    type: SSCMetrics
    cfgs:
      num_classes: 19
