
data:
  datasets:
    type: Occ3D
    splits: [train, val, test]
    data_root: './data/nuscenes'
    frustum_size: 8
  loader:
    batch_size: 16
    num_workers: 4

model:
  channels: 64
  scene_size: [200, 200, 16] # Height, Width, Depth
  downsample_z: 1
  image_shape: (900, 1600)
  voxel_size: 0.4
  volume_scale: 2
  num_classes: 17

evaluator:
  type: SSCMetrics
  num_classes: 17